//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LF_repaso_DSWI_rq.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Negocios2017Entities2 : DbContext
    {
        public Negocios2017Entities2()
            : base("name=Negocios2017Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_abogado> tb_abogado { get; set; }
        public virtual DbSet<tb_categorias> tb_categorias { get; set; }
        public virtual DbSet<tb_clientes> tb_clientes { get; set; }
        public virtual DbSet<tb_empleados> tb_empleados { get; set; }
        public virtual DbSet<tb_paises> tb_paises { get; set; }
        public virtual DbSet<tb_pedidoscabe> tb_pedidoscabe { get; set; }
        public virtual DbSet<tb_productos> tb_productos { get; set; }
        public virtual DbSet<tb_proveedores> tb_proveedores { get; set; }
        public virtual DbSet<tb_pedidosdeta> tb_pedidosdeta { get; set; }
    
        public virtual int USP_ACTUALIZAR(string nom, string dir, string pais, string fono, string cod)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var dirParameter = dir != null ?
                new ObjectParameter("dir", dir) :
                new ObjectParameter("dir", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            var fonoParameter = fono != null ?
                new ObjectParameter("fono", fono) :
                new ObjectParameter("fono", typeof(string));
    
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_ACTUALIZAR", nomParameter, dirParameter, paisParameter, fonoParameter, codParameter);
        }
    
        public virtual int USP_ELIMINAR(string cod)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_ELIMINAR", codParameter);
        }
    
        public virtual ObjectResult<USP_LISTAR_Result> USP_LISTAR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_LISTAR_Result>("USP_LISTAR");
        }
    
        public virtual ObjectResult<USP_LISTAR_CLIENTES_Result> USP_LISTAR_CLIENTES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_LISTAR_CLIENTES_Result>("USP_LISTAR_CLIENTES");
        }
    
        public virtual ObjectResult<USP_LISTARPAISES_Result> USP_LISTARPAISES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_LISTARPAISES_Result>("USP_LISTARPAISES");
        }
    
        public virtual int USP_REGISTRAR(string cod, string nom, string dir, string pais, string fono)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var dirParameter = dir != null ?
                new ObjectParameter("dir", dir) :
                new ObjectParameter("dir", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            var fonoParameter = fono != null ?
                new ObjectParameter("fono", fono) :
                new ObjectParameter("fono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_REGISTRAR", codParameter, nomParameter, dirParameter, paisParameter, fonoParameter);
        }
    }
}
