//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LF_repaso_DSWI_rq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_abogado
    {
        public int Idabog { get; set; }
        public string nomabog { get; set; }
        public string dirabog { get; set; }
        public string idpais { get; set; }
        public Nullable<decimal> sueldo { get; set; }
    
        public virtual tb_paises tb_paises { get; set; }
    }
}
