//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LF_repaso_DSWI_rq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_clientes()
        {
            this.tb_pedidoscabe = new HashSet<tb_pedidoscabe>();
        }
    
        public string IdCliente { get; set; }
        public string NombreCia { get; set; }
        public string Direccion { get; set; }
        public string idpais { get; set; }
        public string Telefono { get; set; }
    
        public virtual tb_paises tb_paises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedidoscabe> tb_pedidoscabe { get; set; }
    }
}
