//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LF_repaso_DSWI_rq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedidosdeta
    {
        public Nullable<int> IdPedido { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public decimal PrecioUnidad { get; set; }
        public short Cantidad { get; set; }
        public double Descuento { get; set; }
    
        public virtual tb_pedidoscabe tb_pedidoscabe { get; set; }
        public virtual tb_productos tb_productos { get; set; }
    }
}
